### ISSUE TITLE
Avoid intermediate screen

### ISSUE THREAD

**Issue by jimmyn** [MONEI/MONEI-WooCommerce#7] opened 2020-04-23 11:25 UTC
@joseconti can we avoid intermediate screen and redirect right away?

![Screen Recording 2020-04-23 at 14 24](https://user-images.githubusercontent.com/5391775/80094042-3d537d80-856e-11ea-9289-d41cd7b5d2e1.gif)

**Comment by alexandresaiz** [comment] 2020-04-24 19:40
@joseconti status here?

**Comment by joseconti** [comment] 2020-04-24 20:26
No, that screen is mandatory @alexandresaiz and @jimmyn. For this reason, I add jQuery on that screen so that you are redirected directly to MONEI, and don't have to press a second pay button to be forwarded to the gateway.

https://github.com/MONEI/MONEI-WooCommerce/blob/master/monei.php#L317

**Comment by jimmyn** [comment] 2020-04-28 13:21
@joseconti I see, then let’s put a white overlay over entire screen with the same loader that appears when you click a checkout button.

**Comment by joseconti** [comment] 2020-04-29 10:36
Ok @jimmyn

**Comment by alexandresaiz** [comment] 2020-05-04 22:59
@joseconti can we close this issue? has it been fixed?

**Comment by alexandresaiz** [comment] 2020-05-08 10:06
@joseconti hello?!

**Comment by joseconti** [comment] 2020-05-11 21:06
Done
![checkout](https://user-images.githubusercontent.com/3383562/81611822-07225480-93dc-11ea-8486-a6b86250aebd.gif)

**Comment by jimmyn** [comment] 2020-05-12 10:20
@joseconti But even your gif shows that there is a flash of intermediate screen and a visible message. Can we avoid that?

**Comment by joseconti** [comment] 2020-05-14 22:27
@jimmyn I know it. But I don't know how to resolve it.
With Credit Card OnSite there isn't this problem because this screen doesn't exist.
The problem is that you have to load the page before you get to the JS that puts the overlay.

**Comment by alexandresaiz** [comment] 2020-05-15 19:59
@jimmyn what should we do here for offsite transactions?

**Comment by joseconti** [comment] 2020-05-18 14:04
All offsite gateways with redirection (posting with a form) have "this problem". It is the WooCommerce work-form.

**Closed** 2021-05-29 07:15 UTC
Labels: enhancement
